/**
 * Content-matched image library for MDF Exports & Imports.
 *
 * Catalogue (only): mangoes · Indian apple · pomegranate · Guntur dry red chilli.
 *
 * Static assets live under public/products/ (pre-generated by
 * scripts/optimize-product-images.mjs) at 480/768/1200/1600 widths in JPG and
 * WebP, plus an LQ placeholder. `unsplash()` picks the JPG width that fits the
 * caller's requested `w`; `unsplashSrcSet()` returns a full multi-width srcset
 * so the browser downloads only the size that matches the viewport (usually
 * 60-95% smaller than the previous unresponsive scheme).
 *
 * Logistics / chilli stills use Unsplash IDs (or the earlier /media/ pattern).
 */

/** First-party produce photos → slug under public/products/. */
const LOCAL_ASSETS = {
  "local-mango-crop": "mango-crop",
  "local-mango-lot": "mango-lot",
  "local-apple-closeup-1": "apple-closeup-1",
  "local-apple-closeup-2": "apple-closeup-2",
  "local-apple-cold-storage": "apple-cold-storage",
  "local-pomegranate-lot": "pomegranate-lot",
  "local-orange-lot": "orange-lot",
};

/** Widths pre-generated for LOCAL_ASSETS (see optimize-product-images.mjs). */
const LOCAL_WIDTHS = [480, 768, 1200, 1600];

function isLocalAsset(id) {
  return Boolean(LOCAL_ASSETS[id]);
}

function localAssetPath(slug, w) {
  return `/products/${slug}-${w}.jpg`;
}

function localAssetWebp(slug, w) {
  return `/products/${slug}-${w}.webp`;
}

function pickLocalAssetWidth(requestedW) {
  // Prefer the smallest variant that meets or exceeds the requested width.
  for (const w of LOCAL_WIDTHS) if (w >= requestedW) return w;
  return LOCAL_WIDTHS[LOCAL_WIDTHS.length - 1];
}

/** Self-hosted logistics assets keyed by Unsplash photo id (without `photo-`). */
const LOCAL_MEDIA = {
  "1494412574643-ff11b0a5c1c3": "container-ship",
  "1605745341112-85968b19335b": "container-port",
  "1512453979798-5ea266f8880c": "dubai",
  "1553413077-190dd305871c": "delivered",
};

function localMediaPath(slug, size) {
  return `/media/${slug}-${size}.jpg`;
}

function pickLocalMediaSize(w) {
  return w <= 720 ? "640" : "1200";
}

/**
 * @param {string} id  Unsplash photo id, or `local-*` first-party key
 * @param {number} [w]
 * @param {number} [q]
 */
export function unsplash(id, w = 1200, q = 80) {
  if (isLocalAsset(id)) {
    return localAssetPath(LOCAL_ASSETS[id], pickLocalAssetWidth(w));
  }
  const slug = LOCAL_MEDIA[id];
  if (slug) return localMediaPath(slug, pickLocalMediaSize(w));
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=${q}`;
}

/**
 * Responsive srcset. Local assets get both WebP variants first (browser picks
 * WebP when it supports both, saving ~15-25% more bytes) followed by JPG.
 *
 * @param {string} id
 * @param {number[]} [widths]
 * @param {number} [q]
 */
export function unsplashSrcSet(id, widths = [384, 480, 640, 768, 1080, 1440, 1920], q = 78) {
  if (isLocalAsset(id)) {
    const slug = LOCAL_ASSETS[id];
    // Browser prefers types earlier in the list; leaving as JPG srcset only
    // (single format) keeps <img srcset> semantics — WebP would need <picture>.
    // Pre-generated widths are 480/768/1200/1600.
    return LOCAL_WIDTHS.map((w) => `${localAssetPath(slug, w)} ${w}w`).join(", ");
  }
  const slug = LOCAL_MEDIA[id];
  if (slug) {
    return `${localMediaPath(slug, "640")} 640w, ${localMediaPath(slug, "1200")} 1200w`;
  }
  return widths.map((w) => `${unsplash(id, w, q)} ${w}w`).join(", ");
}

/**
 * WebP srcset for local assets — useful with <picture><source type="image/webp">.
 * Returns undefined for remote / non-local images (Unsplash already negotiates
 * format via `?auto=format`).
 */
export function localWebpSrcSet(id) {
  if (!isLocalAsset(id)) return undefined;
  const slug = LOCAL_ASSETS[id];
  return LOCAL_WIDTHS.map((w) => `${localAssetWebp(slug, w)} ${w}w`).join(", ");
}

/** @param {string} id */
export function unsplashLQ(id) {
  if (isLocalAsset(id)) {
    return `/products/${LOCAL_ASSETS[id]}-lq.jpg`;
  }
  const slug = LOCAL_MEDIA[id];
  if (slug) return localMediaPath(slug, "lq");
  return `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=32&q=20&blur=20`;
}

/**
 * Product catalogue stills. One primary photo per live SKU.
 * Mango / apple / pomegranate use first-party export photography.
 */
export const productImages = {
  /** Bulk harvest lot — products showcase, drawers, hero fresh card */
  mangoes: "local-mango-lot",
  /** Orchard / on-tree crop — Banganapalli product landing hero */
  mangoCrop: "local-mango-crop",
  indianApple: "local-apple-closeup-1",
  indianAppleDetail: "local-apple-closeup-2",
  appleColdStorage: "local-apple-cold-storage",
  pomegranate: "local-pomegranate-lot",
  orangeLot: "local-orange-lot",
  dryRedChilli: "1766158554170-1e8b1899c8ae",
  /** Rich artistic detail — hero shot of dried black peppercorns */
  blackPepper: "1755598603006-5cee23c4cb4e",
  /** Origin: pepper on the vine — green berries, pre-harvest agricultural shot */
  blackPepperVine: "1706707250965-1a0455b67fec",
  /** Production: clean bowl of graded peppercorns */
  blackPepperBowl: "1649952052743-5e8f37c348c5",
};

/**
 * Narrative scenes. Keys describe the story beat, not a random crop.
 * Mango beats use first-party photos; other beats stay stock until replaced.
 */
export const scenes = {
  farmSunrise: "1500382017468-9049fed747ef",

  /** Mangoes on the tree — first-party crop */
  mangoOrchard: "local-mango-crop",

  growerHands: "1570913149827-d2ac84ab3f9a",

  gradedApples: "1567306226416-28f0efdc88ce",

  harvestCollect: "1625238780743-d7b5b0bec6ed",

  /** Packed / lot mango — first-party */
  mangoCrates: "local-mango-lot",

  chilliLots: "1763994685403-88aaa750af61",

  chilliDried: "1526576935508-6bccc1e07580",

  warehouse: "1553413077-190dd305871c",

  portTerminal: "1494412574643-ff11b0a5c1c3",

  vesselAtSea: "1605745341112-85968b19335b",

  dubai: "1512453979798-5ea266f8880c",

  // --- Back-compat aliases (mango → first-party) ---
  farmField: "local-mango-crop",
  farmer: "1570913149827-d2ac84ab3f9a",
  growerPortrait: "1570913149827-d2ac84ab3f9a",
  harvest: "local-mango-crop",
  packaging: "local-mango-lot",
  crates: "1625238780743-d7b5b0bec6ed",
  market: "local-mango-lot",
  containerShip: "1605745341112-85968b19335b",
  containerPort: "1494412574643-ff11b0a5c1c3",
  delivered: "1553413077-190dd305871c",
};

/**
 * Gallery. Prefer first-party produce lots; keep logistics / chilli stock.
 * @type {{ id: string, caption: string, alt: string }[]}
 */
export const galleryItems = [
  {
    id: productImages.mangoCrop,
    caption: "Mangoes on the tree",
    alt: "Green mangoes hanging from orchard branches in Andhra Pradesh",
  },
  {
    id: productImages.mangoes,
    caption: "Mango harvest lot",
    alt: "Large lot of freshly harvested mangoes ready for packing",
  },
  {
    id: productImages.indianApple,
    caption: "Kinnaur apple. Graded close-up",
    alt: "Export-grade Kinnaur red apples packed in a carton",
  },
  {
    id: productImages.indianAppleDetail,
    caption: "Kinnaur apple detail",
    alt: "Close-up of deep red Kinnaur apples in packing",
  },
  {
    id: productImages.appleColdStorage,
    caption: "Apple cold storage",
    alt: "Apples packed in wooden crates inside a cold storage facility",
  },
  {
    id: productImages.pomegranate,
    caption: "Pomegranate harvest lot",
    alt: "Large outdoor lot of harvested pomegranates being packed",
  },
  {
    id: productImages.orangeLot,
    caption: "Citrus harvest lot",
    alt: "Large outdoor lot of harvested oranges on a tarp",
  },
  {
    id: productImages.dryRedChilli,
    caption: "Guntur dry red chilli",
    alt: "Close-up pile of dried red chillies",
  },
  {
    id: productImages.blackPepper,
    caption: "Malabar black pepper",
    alt: "Rich close-up of whole dried black peppercorns from the Malabar coast",
  },
  {
    id: productImages.blackPepperVine,
    caption: "Pepper on the vine",
    alt: "Green pepper berries growing on the vine before harvest",
  },
  {
    id: scenes.portTerminal,
    caption: "Loaded at origin port",
    alt: "Container terminal at the origin port",
  },
  {
    id: scenes.vesselAtSea,
    caption: "Bound for Gulf markets",
    alt: "Container ship under way toward destination markets",
  },
];

/** @deprecated Prefer galleryItems. Kept so older imports do not crash during HMR. */
export const galleryImages = galleryItems.map((g) => g.id);
