import { site } from "@/lib/config";
import { cn } from "@/lib/utils";

// Optimized brand mark — palette-quantized PNG served from public/products/
// (generated by scripts/optimize-product-images.mjs). Kept out of Vite's JS
// bundle graph, cached long-term. Dark-mode-only site: always the light mark.
const logoLight = "/products/logo-light.png";

/** Cropped wordmark aspect ≈ 2.5:1 (LightPNG 1039×413 / DarkPNG 935×378). */
const SIZE = {
  /** Fills nav row height without growing the bar. */
  nav: {
    width: 250,
    height: 100,
    img: "h-10 w-auto max-w-[min(50vw,16rem)] origin-left sm:max-w-[18rem]",
  },
  /** Extra-large brand presence for the footer. */
  footer: {
    width: 420,
    height: 168,
    img: "h-[4.5rem] w-auto max-w-[min(88vw,22rem)] sm:h-24 sm:max-w-[26rem] md:h-28 md:max-w-[30rem] lg:h-32 lg:max-w-[34rem]",
  },
};

/**
 * MDF brand mark (PNG). Dark-only site: always the light (white) wordmark.
 * `inverted` and theme are no-ops now, kept in the signature so existing
 * call-sites don't need to change.
 */
export function Logo({ className, onClick, size = "nav" }) {
  const src = logoLight;
  const preset = SIZE[size] || SIZE.nav;

  return (
    <a
      href="#top"
      onClick={onClick}
      className={cn(
        "group inline-flex shrink-0 items-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2",
        size === "nav" && "h-10",
        className
      )}
      aria-label={`${site.name}. Home`}
    >
      <img
        src={src}
        alt={site.name}
        width={preset.width}
        height={preset.height}
        decoding="async"
        className={cn(
          // Source is ~4× nav CSS size so browser downscale stays sharp
          "object-contain object-left transition-[filter] duration-500 ease-premium group-hover:brightness-110",
          preset.img
        )}
      />
    </a>
  );
}
